// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.MainModule.Models;

#nullable disable

namespace modular.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20220116174732_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Modules.MainModule.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Modules.MainModule.Models.Todo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDone")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "Fk_User");

                    b.ToTable("Todo", (string)null);
                });

            modelBuilder.Entity("Modules.MainModule.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mail");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pass");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Username", "Mail" }, "Unique_Username_Mail")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Modules.MainModule.Models.UserRol", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RolesId" }, "User_Rol_Fk_Rol");

                    b.HasIndex(new[] { "UserId" }, "User_Rol_Fk_User");

                    b.ToTable("User_Rol", (string)null);
                });

            modelBuilder.Entity("Modules.MainModule.Models.Todo", b =>
                {
                    b.HasOne("Modules.MainModule.Models.User", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.MainModule.Models.UserRol", b =>
                {
                    b.HasOne("Modules.MainModule.Models.Role", "Roles")
                        .WithMany("UserRols")
                        .HasForeignKey("RolesId")
                        .IsRequired()
                        .HasConstraintName("User_Rol_Fk_Rol");

                    b.HasOne("Modules.MainModule.Models.User", "User")
                        .WithMany("UserRols")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("User_Rol_Fk_User");

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.MainModule.Models.Role", b =>
                {
                    b.Navigation("UserRols");
                });

            modelBuilder.Entity("Modules.MainModule.Models.User", b =>
                {
                    b.Navigation("Todos");

                    b.Navigation("UserRols");
                });
#pragma warning restore 612, 618
        }
    }
}
